# Generated by Django 2.1.7 on 2019-02-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TopModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('children', models.ForeignKey(null=True, on_delete=True, to='api.OneInner')),
            ],
        ),
        migrations.CreateModel(
            name='TwoInner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('children', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='oneinner',
            name='children',
            field=models.ForeignKey(null=True, on_delete=True, to='api.TwoInner'),
        ),
    ]
