# Generated by Django 2.1.7 on 2019-02-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190218_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threeinner',
            name='children',
        ),
    ]
