# Generated by Django 2.1.7 on 2019-02-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_threeinner_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneinner',
            name='children',
        ),
        migrations.AddField(
            model_name='oneinner',
            name='children',
            field=models.ManyToManyField(null=True, to='api.TwoInner'),
        ),
        migrations.RemoveField(
            model_name='topmodel',
            name='children',
        ),
        migrations.AddField(
            model_name='topmodel',
            name='children',
            field=models.ManyToManyField(null=True, to='api.OneInner'),
        ),
        migrations.RemoveField(
            model_name='twoinner',
            name='children',
        ),
        migrations.AddField(
            model_name='twoinner',
            name='children',
            field=models.ManyToManyField(null=True, to='api.ThreeInner'),
        ),
    ]
