# Generated by Django 2.1.7 on 2019-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190218_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneinner',
            name='children',
        ),
        migrations.AddField(
            model_name='oneinner',
            name='children',
            field=models.ForeignKey(null=True, on_delete=True, to='api.TwoInner'),
        ),
        migrations.RemoveField(
            model_name='topmodel',
            name='children',
        ),
        migrations.AddField(
            model_name='topmodel',
            name='children',
            field=models.ForeignKey(null=True, on_delete=True, to='api.OneInner'),
        ),
    ]
