# Generated by Django 2.1.7 on 2019-02-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190218_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoinner',
            name='children',
        ),
        migrations.AddField(
            model_name='twoinner',
            name='children',
            field=models.ForeignKey(null=True, on_delete=True, to='api.ThreeInner'),
        ),
    ]
