# Generated by Django 2.1.7 on 2019-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190218_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twoinner',
            name='children',
        ),
        migrations.AddField(
            model_name='twoinner',
            name='children',
            field=models.ManyToManyField(null=True, to='api.ThreeInner'),
        ),
    ]
