# Generated by Django 2.1.7 on 2019-02-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190218_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oneinner',
            name='children',
        ),
        migrations.AddField(
            model_name='oneinner',
            name='children',
            field=models.ManyToManyField(null=True, to='api.TwoInner'),
        ),
        migrations.RemoveField(
            model_name='topmodel',
            name='children',
        ),
        migrations.AddField(
            model_name='topmodel',
            name='children',
            field=models.ManyToManyField(null=True, to='api.OneInner'),
        ),
    ]
