# Generated by Django 2.1.7 on 2019-02-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190218_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneinner',
            name='children',
            field=models.ManyToManyField(related_name='children_two', to='api.TwoInner'),
        ),
        migrations.AlterField(
            model_name='topmodel',
            name='children',
            field=models.ManyToManyField(related_name='children_one', to='api.OneInner'),
        ),
        migrations.AlterField(
            model_name='twoinner',
            name='children',
            field=models.ManyToManyField(related_name='children_three', to='api.ThreeInner'),
        ),
    ]
